### ISSUE TITLE
Unable to get the Output folder

### ISSUE THREAD

**Issue by Gautamshahi** [SDM-TIB/SDM-RDFizer-Experiments#2]
Hello, 

I have followed the instructions given in the video. I am not able to get the output folder. Everything is running fine. Can you please help me to rectify the issue?

![image](https://user-images.githubusercontent.com/3966230/88467809-61ab5700-cedb-11ea-82ba-6b74120f5c3d.png)

**Comment by mevs** [comment]
Many thanks for contacting us.

Since the output wasn't generated automatically this could mean that one of the following could have happened:
- The files weren't properly uploaded to the docker container. To check this please run docker logs CONTAINER_ID. If the log says that your files don't exist, that means the files weren't properly uploaded. As a simpler way to upload the files, you can copy the files to the example folder in the root directory of the SDM-RDFier and upload the data from there. Please note that configuration and mapping files must reflect the fact that they're in the container. Also, when uploading the data, please use the complete path to the data.
- The other case is that you might have to download the output folder from the container by executing this command 
docker cp CONTAINER_ID:/app/path/to/output.

As an alternative, you can run the SDM-RDFizer directly from the terminal by using Python.
pip3 install -r requeriments.txt
python3 rdfizer/run_rdfizer.py /path/to/config/FILE
In this case, the mapping and configuration files must reflect the fact that you're executing the SDM-RDFizer locally, meaning the path must indicate the location of the files within your file system.

Thank you again.

**Comment by dachafra** [comment]
A repeated issue, related to the engine, not to the experiments, to see updates go to https://github.com/SDM-TIB/SDM-RDFizer/issues/28
